### ISSUE TITLE
What about the support of English in the onhover tooltips?

### ISSUE THREAD

**Issue by krasnovpro** [thqby/vscode-autohotkey2-lsp#1]

**Comment by thqby** [comment]
You can modify [syntaxes\ahk2.d.ahk](https://github.com/thqby/vscode-autohotkey2-lsp/blob/master/syntaxes/ahk2.d.ahk)(about functions and classes) and [syntaxes\ahk2.json](https://github.com/thqby/vscode-autohotkey2-lsp/blob/master/syntaxes/ahk2.json)(about keywords and other snippets) files.

**Comment by Lexikos** [comment]
Most of it could be generated by parsing the HTML documentation. That would be much less tedious than doing it by hand, and could be applied to all languages that have documentation.

**Comment by lord-ne** [comment]
A large potion of it could be done just by reading the definitions from the tables in the [alphabetical function index](https://lexikos.github.io/v2/docs/commands/index.htm) and the [built-in variable list](https://lexikos.github.io/v2/docs/Variables.htm#BuiltIn). It wouldn't be as in-depth as what we could get by reading individual function pages, but it would be much simpler since we wouldn't have to worry about what to include from each page or how to represent the formatting. If I have time I'll look into it tomorrow.

**Comment by lord-ne** [comment]
@thqby How did you generate the syntax files? Did you do it all manually?

**Comment by thqby** [comment]
I'm modifying from the javascript syntax file

**Comment by krasnovpro** [comment]
It would be nice if all ahk-plugin developers got together and made one powerful plugin, instead of dozens of unfinished ones like now.
