### ISSUE TITLE
Autocompletion for prototype object methods

### ISSUE THREAD

**Issue by Descolada** [thqby/vscode-autohotkey2-lsp#155]
Autocompletion (arguments recommendation) is not showing up when using prototype objects:
![image](https://user-images.githubusercontent.com/16986957/184577304-8f3c990f-b4fb-4ca8-a71c-f31f41e643e2.png)

Compared to using a new object:
![image](https://user-images.githubusercontent.com/16986957/184577273-202df269-bbb9-4ebc-9bd2-78c6139ce3cf.png)

The issue persists even if the function is marked as static.

**Comment by RaptorX** [comment]
I think the first example is an error.

`MyTest.MyFunc()` *must be a static function* for it to work. I think you would even get an error by AHK if you try that code.

Here is what I get:
![image](https://user-images.githubusercontent.com/328761/184666631-32ef651f-8cd4-4620-bce9-a3e7c80952d3.png)

The correct way for the lexer to handle it is to mark it as a problem because you cannot access an instance method as a class method.

**Comment by thqby** [comment]
You can define new methods for classes elsewhere, so this may be correct

**Comment by RaptorX** [comment]
> You can define new methods for classes elsewhere, so this may be correct

Yes that is correct. I was referring specifically to his first example.
Which begs the question whether the lexer can use the language server to confirm if the base class has a static method defined, if not it should mark it as an error.
