### ISSUE TITLE
Sublime text?

### ISSUE THREAD

**Issue by DonovanZeanah** [thqby/vscode-autohotkey2-lsp#204]
I saw your post about getting it to work in sublime text? I would LOVE to get this working, but couldn't quite understand the setup? Is there a certain place I  should place the folder? this is what i have in my sublime preferences.sublime-settings file:
```
  "clients": {
        "ahk2-lsp": {
            "enabled": true,
            "command": ["node.exe", "d:/ahk/vscode-autohotkey2-lsp/server/dist/server.js", "--stdio"], // Update the PATH
            "selector": ["source.ahk2", "source.ah2"],
            "env": {
                "AHK2_LS_CONFIG": "{\"locale\":\"en-us\",\"InterpreterPath\":\"C:/Program Files/Autohotkey/AutoHotkey32.exe\",\"AutoLibInclude\":0}",
            },
            "schemes": ["file", "buffer", "res"],
        },
    },
```

**Comment by thqby** [comment]
In Sublime Text4, first install the lsp for sublime text plug-in (Package Control: Install Package - LSP).
![image](https://user-images.githubusercontent.com/28240311/197315077-b9e252bf-43ff-44f1-a388-a59256493395.png)

![image](https://user-images.githubusercontent.com/28240311/197315139-bcba77ef-b1e6-424d-a3c4-dc5ff99ea505.png)
then download [vscode-ahk2-lsp](https://github.com/thqby/vscode-autohotkey2-lsp/tree/server).

![image](https://user-images.githubusercontent.com/28240311/197315167-3eb213a3-189c-4470-99c8-59eb70b6a944.png)
![image](https://user-images.githubusercontent.com/28240311/197315190-0b73fd90-8de9-46ea-8910-ec804ac8ce38.png)
and then add the language server to the lsp configuration file instead of the editor configuration file.

In addition, syntax highlighting needs to be reimplemented in the editor, and ahk2-lsp provides semantic highlighting (does the editor support it?), Intellisense, symbol renaming, document symbol, parameter prompt, formatting and other features.

**Comment by thqby** [comment]
[AutoHotkey2.sublime-syntax.zip](https://github.com/thqby/vscode-autohotkey2-lsp/files/9843973/AutoHotkey2.sublime-syntax.zip)
This is a simple sublime syntax highlighting, in the path `C:\Users\username\AppData\Roaming\Sublime Text\Packages\User\LSP-ahk2\AutoHotkey2.sublime-syntax`
