### ISSUE TITLE
Changes for upcoming v2.1-alpha.3

### ISSUE THREAD

**Issue by Lexikos** [thqby/vscode-autohotkey2-lsp#367]
As of AutoHotkey/AutoHotkey@a09efc35fe9445c6dcf9f7cdb32eda5f08634d7a, `Throw` is a function, so these are valid:
```AutoHotkey
(true) ? throw() : ""
throw(Error()), MsgBox()
SetTimer throw.Bind(Error('Oops!')), -1
```
It is still a reserved word, so attempting to shadow it with a local variable will raise an error at load time (and of course, it is read-only).

Throw is now continuable, so lines following it are not assumed to be unreachable.

More details in AutoHotkey/AutoHotkeyDocs@257b6e4a2948c385a87c48d9b263475b14efe239.

<hr />

As of AutoHotkey/AutoHotkey@19e4128c5bd2319244c5403e1850d874867171e0, function definitions can be embedded inside expressions. Examples and details in AutoHotkey/AutoHotkeyDocs@5bc2ad2a77038eee580f7b4d8048f91b280a3f0e.

**Comment by Lexikos** [comment]
As of AutoHotkey/AutoHotkey@30ad2e92908515b1ab3093e5e5b209e152abd1cb, anonymous function definition expressions are permitted.
```AutoHotkey
SetTimer(() {
    MsgBox "5 second timer expired."
}, -5000)
```

**Comment by PythonYunfei** [comment]
Guido van Rossum, Father of Python, said in Zen of Python:" Flat is better than nested".
![image](https://github.com/AutoHotkey/AutoHotkey/assets/47076058/fec759a4-6d94-40d6-a9c9-aba7b3e86008)
So, I wish this feature could be limited back:
![image](https://github.com/AutoHotkey/AutoHotkey/assets/47076058/65800020-f8ae-486d-969d-d59fdf3d9b54)
As said by Guido van Rossum in his official website criticizing JavaScript, if this above usage is abused, the readability of code will decrease significantly. Therefore, unlike JS, he forbids this feature by design in Python.
A code reader reading flat blocks without nesting one by one, seems easier. However, it will become more difficult and really much slower to read, when one block is nested by another too many times.
