### ISSUE TITLE
an problem about RButton::{ switch

### ISSUE THREAD

**Issue by ZhuangQu** [thqby/vscode-autohotkey2-lsp#379]
```
RButton::{
    switch {
    }
}
```
The last `}` is reported wrong (but not wrong), and is formatted to
```
RButton::{
switch {
}
}
```

**Comment by zachpoblete** [comment]
It actually happens in any hotkey that uses the one true brace style.
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/92368853/759d11b2-cd8a-4e22-8365-4b2cd90d3579)

**Comment by Github-Jackson** [comment]
It currently only seems to work in hotkey tags(one true brace style).
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/53117644/c7573c7e-84d2-406d-af04-dcc56a738af8)

This is normal in the following cases :
```ahk2
#T::
{
}
::test::{
}
```
---
The problem seems to stem from this @https://github.com/thqby/vscode-autohotkey2-lsp/commit/7411ae53a434beea314e9e18a4320d8e9ce1b3ed ( I'm not sure. I hope I can help you!)

Thanks to this extension, it makes ahk2's codeing happy!

**Comment by thqby** [comment]
broken by 9571466ef427432a9ab08a684ed1dd669e64f863
