### ISSUE TITLE
#Include with brackets failing to find libraries

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#448]
Type: <b>Bug</b>

Using `#include` with a new project is having issues when using bracket syntax as opposed to using paths as shown in the image below:

![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/328761/b72787ad-0cd9-450f-9a02-fa9326e30d74)

Restarting vscode is not fixing the issue.

---

Extension version: 2.2.8
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (19.54GB free)|
|Process Argv|--crash-reporter-id 3e042e59-cb22-4371-968a-6f3e35abe666|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by thqby** [comment]
Not enough information to reproduce.

**Comment by fashionableDark** [comment]
> Not enough information to reproduce.

Steps to reproduce:

1. Create a new folder and open it in VSCode
2. Create a `lib` folder and `blah` folder
3. Create `common.ahk` in the `lib` folder
4. Write a function in `common.ahk`:

    ```ahk
    Hello()
    {
        MsgBox("Hello")
    }
    ```

5. Create `code.ahk` in the `blah` folder
6. Add to it:

    ```ahk
    #Include <common>

    Hello()
    ```

7. Set language to ahk2 if it isn't already
8. See errors "Invalid file path" and "Variable 'Hello' appears to never be assigned a value"


If you add a `main.ahk` to the root and include "blah\code.ahk", it will run properly despite the parser errors while `blah.ahk` will not run on its own because AHK is looking for `common.ahk` in `%A_ScriptDir%\lib` (relative to the running script of course). To get working syntax highlighting with `main.ahk` you need to set `AutoHotkey2.WorkingDirs`, but annoyingly, it doesn't support the VSCode variable `${workspaceFolder}`, so it has to be hard-coded.

**Comment by PythonYunfei** [comment]
把${workspaceFolder}换成${file}或许可以试一下..

**Comment by fashionableDark** [comment]
> 把${workspaceFolder}换成${file}或许可以试一下..

Nope, neither ${file} nor ${fileWorkspaceFolder} worked for me in any variation I tried.
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/145222067/023d9d83-e38a-4b90-9519-f2c8139a7d20)

**Comment by thqby** [comment]
you can open `main.ahk` first, then open `blah\code.ahk`.

**Comment by PythonYunfei** [comment]
现在发现。就算获得了脚本文件夹路径。还是要把所有导入到该路径的#include<XXX> 检验一遍。
存在因为打开先后顺序的不同，而自相矛盾的地方。麻烦，不太值得继续做进一步的改进了。
