### ISSUE TITLE
[Wish] Update File Version would update ;@Ahk2Exe-SetVersion

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#565]
It would be nice if the Update File Version function updates the `@version` property of the first JSDoc comment in the script but also any `;@Ahk2Exe-SetVersion` found as well, as they are usually the same thing.

**Comment by RaptorX** [comment]
I dont think it is working at the moment, is there any special syntax for this?

**Comment by mark-wiemer** [comment]
I don't think the change has been released yet :)

**Comment by thqby** [comment]
Failed when line comments exist on the previous line of the instruction, correct?

**Comment by RaptorX** [comment]
> I don't think the change has been released yet :)

It was marked as completed a few hours ago. 



> Failed when line comments exist on the previous line of the instruction, correct?

Yes, I have other `ahk2exe` comments right above it

**Comment by mark-wiemer** [comment]
Yes, the issue is closed as completed, but generally that does not mean the fix has been released. This is true for thqby's extension, AHK++, and most codebases I've worked with. Usually issues are closed once the code is updated, but there is a delay between updating the code and releasing an updated package. You'll see thqby's extension hasn't been updated since yesterday, so you won't see the changes quite yet. Expect this to be fully resolved when 2.5.2 comes out :)

https://marketplace.visualstudio.com/items?itemName=thqby.vscode-autohotkey2-lsp

![image](https://github.com/user-attachments/assets/4d10e62c-2d75-472f-9157-5569963f3dc3)

**Comment by RaptorX** [comment]
> Yes, the issue is closed as completed, but generally that does not mean the fix has been released. This is true for thqby's extension, AHK++, and most codebases I've worked with. Usually issues are closed once the code is updated, but there is a delay between updating the code and releasing an updated package. You'll see thqby's extension hasn't been updated since yesterday, so you won't see the changes quite yet. Expect this to be fully resolved when 2.5.2 comes out :)
> 

Oh I see. I didn't know that.
